"""GENERATE the spec-side DECLARATION (specs/0042 §4a: one row per point — id · governing spec · the
§6 invariant it enforces · file:symbol — authored, not scraped) from the AUTHORED semantic review
(the plan's E entries were written by reading every candidate) with the symbol taken from the
inventory's qualname at the reviewed line. The output is a Python module carrying a frozen tuple
of rows, committed as specs/evidence/0042/declaration.py; INV-1's two sources are then this file
(EXPECTED) and the sites (OBSERVED), and drift refuses in both directions.

Usage: declaration_gen.py <inventory OUTPUT.json> <semantic_review.py> <out.py>"""
import importlib.util, json, pathlib, sys, collections


def _strict_pairs(pairs):
    """0026's evidence-boundary rule: a duplicate key is a REFUSAL, never last-wins."""
    out = {}
    for k, v in pairs:
        if k in out:
            raise ValueError(f"duplicate key {k!r}")
        out[k] = v
    return out

inv_path, review_path, out_path = (pathlib.Path(a) for a in sys.argv[1:4])
inv = {(s["module"], s["line"]): s for s in json.load(open(inv_path), object_pairs_hook=_strict_pairs)["sites"]}
spec = importlib.util.spec_from_file_location("review", review_path); review = importlib.util.module_from_spec(spec); spec.loader.exec_module(review)

rows = {}
for (module, line), (sid, spec_, inv_, label) in review.E.items():
    site = inv[(module, line)]
    symbol = f"{module}:{site['qualname']}"
    r = rows.setdefault(sid, {"id": sid, "spec": spec_, "invariant": inv_, "label": label, "symbols": set()})
    assert (r["spec"], r["invariant"], r["label"]) == (spec_, inv_, label), f"{sid}: the review gives one id two contracts"
    r["symbols"].add(symbol)
for sid, r in rows.items():
    assert len(r["symbols"]) == 1, f"{sid} spans symbols {sorted(r['symbols'])} — one id, one function"

lines = ['"""specs/0042 §4a — THE DECLARATION: one row per enforcement point — id · governing spec · the §6',
         'invariant it enforces · file:symbol · the decision label. AUTHORED, not scraped: every row comes from',
         'the semantic review (specs/evidence/0042/semantic_review.py), a decision written by reading the',
         'candidate, never from a scan of `declare_site` calls; the sites are INV-1\'s OTHER source, and',
         '`tests/test_0042_reconciliation.py` refuses drift in both directions. Regenerated by',
         'specs/evidence/0042/declaration_gen.py; a hand edit here is a review change and belongs in the review."""',
         '', 'DECLARATION = (']
for sid in sorted(rows):
    r = rows[sid]; sym = next(iter(r["symbols"]))
    lines.append(f'    ("{sid}", "{r["spec"]}", "{r["invariant"]}", "{sym}", "{r["label"]}"),')
lines += [')', '', 'DECLARED_IDS = frozenset(row[0] for row in DECLARATION)', '',
          'assert len(DECLARED_IDS) == len(DECLARATION), "duplicate id in the declaration"', '']
pathlib.Path(out_path).write_text("\n".join(lines))
by_spec = collections.Counter(r["spec"] for r in rows.values())
print(f"declaration.py: {len(rows)} rows | specs: {len(by_spec)} | top: {by_spec.most_common(5)}")
