# the OVERRIDE literal exactly as authored at plan time (keys = plan-time inventory lines); never rewritten
OVERRIDE = {  # (module, line) -> reason class, where the module default is not the truth for that line
    ("__init__.py", 376): "control-flow", ("__init__.py", 456): "control-flow", ("__init__.py", 584): "control-flow",
    ("__init__.py", 900): "control-flow", ("__init__.py", 1458): "control-flow", ("__init__.py", 1599): "control-flow",
    ("__init__.py", 1621): "control-flow", ("__init__.py", 1670): "control-flow", ("__init__.py", 1677): "control-flow",
    ("__init__.py", 1688): "control-flow", ("__init__.py", 1695): "control-flow", ("__init__.py", 1724): "control-flow",
    ("__init__.py", 1750): "control-flow", ("__init__.py", 2027): "internal-invariant", ("__init__.py", 2075): "control-flow",
    ("__init__.py", 278): "internal-invariant", ("__init__.py", 285): "internal-invariant",
    ("__init__.py", 977): "internal-invariant", ("__init__.py", 981): "internal-invariant", ("__init__.py", 985): "internal-invariant",
    ("__init__.py", 992): "internal-invariant", ("__init__.py", 994): "internal-invariant",
    ("agreement.py", 219): "predicate-helper", ("agreement.py", 267): "control-flow", ("agreement.py", 487): "control-flow",
    ("asof/adapter.py", 53): "internal-invariant", ("asof/resolve.py", 114): "internal-invariant", ("asof/resolve.py", 119): "internal-invariant",
    ("asof/resolve.py", 176): "control-flow", ("asof/resolve.py", 201): "predicate-helper",
    ("compile.py", 168): "predicate-helper", ("diagnostics.py", 211): "predicate-helper", ("diagnostics.py", 244): "predicate-helper",
    ("doctor.py", 376): "predicate-helper", ("dryrun.py", 68): "predicate-helper",
    ("graph.py", 41): "predicate-helper", ("graph.py", 56): "predicate-helper", ("graph.py", 213): "internal-invariant",
    ("graph.py", 866): "argument-check", ("grounding.py", 153): "control-flow",
    ("ingest.py", 173): "control-flow", ("ingest.py", 125): "argument-check",
    ("lifecycle.py", 184): "control-flow", ("lifecycle.py", 323): "control-flow",
    ("portability.py", 416): "control-flow",
    ("procedural_gate.py", 43): "argument-check", ("procedures.py", 99): "control-flow", ("procedures.py", 358): "control-flow",
    ("scope.py", 169): "predicate-helper", ("scope.py", 209): "internal-invariant", ("scope.py", 212): "internal-invariant",
    ("scope.py", 214): "internal-invariant", ("scope.py", 363): "predicate-helper", ("scope.py", 570): "control-flow", ("scope.py", 662): "control-flow",
    ("scope_linkage.py", 108): "control-flow", ("scope_linkage.py", 119): "control-flow", ("scope_linkage.py", 501): "predicate-helper",
    ("scope_linkage.py", 502): "predicate-helper", ("scope_linkage.py", 523): "control-flow",
    ("schema.py", 62): "control-flow", ("schema.py", 235): "predicate-helper", ("schema.py", 242): "predicate-helper",
    ("schema.py", 324): "predicate-helper", ("schema.py", 516): "predicate-helper", ("schema.py", 606): "internal-invariant",
    ("schema.py", 611): "internal-invariant", ("schema.py", 633): "internal-invariant", ("schema.py", 638): "internal-invariant",
    ("schema.py", 679): "predicate-helper", ("schema.py", 750): "predicate-helper", ("schema.py", 311): "internal-invariant", ("schema.py", 674): "internal-invariant",
    ("store/sqlite.py", 119): "control-flow", ("store/sqlite.py", 193): "control-flow", ("store/sqlite.py", 243): "control-flow",
    ("store/sqlite.py", 302): "control-flow", ("store/sqlite.py", 384): "control-flow", ("store/sqlite.py", 609): "control-flow",
    ("store/sqlite.py", 628): "control-flow", ("store/sqlite.py", 672): "control-flow", ("store/sqlite.py", 737): "control-flow",
    ("store/sqlite.py", 753): "predicate-helper", ("store/sqlite.py", 907): "control-flow", ("store/sqlite.py", 1836): "control-flow",
    ("store/sqlite.py", 1861): "control-flow", ("store/sqlite.py", 1870): "predicate-helper", ("store/sqlite.py", 101): "argument-check",
    ("store/sqlite.py", 282): "argument-check", ("store/sqlite.py", 1932): "argument-check", ("store/sqlite.py", 2203): "argument-check",
    ("store/sqlite.py", 2218): "argument-check", ("store/sqlite.py", 277): "control-flow", ("store/sqlite.py", 621): "control-flow",
    ("store/sqlite.py", 1184): "control-flow", ("store/sqlite.py", 1457): "control-flow", ("store/sqlite.py", 1469): "control-flow",
    ("store/sqlite.py", 1484): "control-flow", ("store/sqlite.py", 2138): "control-flow", ("store/sqlite.py", 2159): "control-flow",
    ("store/sqlite.py", 2221): "control-flow", ("store/sqlite.py", 1909): "argument-check",
    ("store/revocation.py", 56): "predicate-helper", ("store/revocation.py", 109): "control-flow", ("store/revocation.py", 142): "control-flow",
    ("store/revocation_sweep.py", 166): "control-flow", ("store/revocation_sweep.py", 186): "control-flow",
    ("store/schema_version.py", 1609): "argument-check", ("store/schema_version.py", 1778): "control-flow",
    ("telemetry.py", 453): "control-flow", ("telemetry.py", 474): "control-flow", ("telemetry.py", 501): "control-flow",
    ("mcp_server.py", 548): "cli-usage", ("mcp_server.py", 554): "cli-usage", ("mcp_server.py", 558): "cli-usage", ("mcp_server.py", 570): "cli-usage",
    ("source_identity.py", 59): "argument-check", ("_json.py", 43): "control-flow", ("introspect.py", 54): "argument-check",
}
